version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Kolkata
    assignees:
      - waduhek

  - package-ecosystem: docker
    directories:
      - "/"
      - "/nginx"
      - "/otelcol"
    schedule:
      interval: weekly
      timezone: Asia/Kolkata
    assignees:
      - waduhek

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Kolkata
    assignees:
      - waduhek
