dist:
  name: website-otelcol
  description: OTel collector for collecting signals from the the application service and DB instances and exporting them to AWS.
  output_path: ./build
  version: 0.4.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.141.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.141.0
  - gomod:
      go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.141.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.141.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.141.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.141.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.141.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.47.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.47.0

extensions:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.141.0

connectors:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/connector/grafanacloudconnector v0.141.0
