dist:
  name: website-otelcol
  description: OTel collector for collecting signals from the the website server.
  output_path: ./build
  version: 0.6.5

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.146.1
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.146.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.146.1
  - gomod:
      go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.146.1
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.146.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.146.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.146.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.146.1
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.146.1

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.52.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.52.0

extensions:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.146.0

connectors:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/connector/grafanacloudconnector v0.146.0
